// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj4XyMCuZIPDJIU2lclg5k1yxseSKFQg4',
    appId: '1:557980351039:web:3cadb671af35a366fb568a',
    messagingSenderId: '557980351039',
    projectId: 'mopelis-ca195',
    authDomain: 'mopelis-ca195.firebaseapp.com',
    storageBucket: 'mopelis-ca195.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUgdql7Jt9XKJoC_B9VjU22LufVV8Oc5Q',
    appId: '1:557980351039:android:12eb84546b4d5007fb568a',
    messagingSenderId: '557980351039',
    projectId: 'mopelis-ca195',
    storageBucket: 'mopelis-ca195.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqr-fwf1JtE5XXW5-mcJ3Csv8jrnRSa6I',
    appId: '1:557980351039:ios:4d9588282ce1da36fb568a',
    messagingSenderId: '557980351039',
    projectId: 'mopelis-ca195',
    storageBucket: 'mopelis-ca195.firebasestorage.app',
    iosBundleId: 'com.example.movil2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqr-fwf1JtE5XXW5-mcJ3Csv8jrnRSa6I',
    appId: '1:557980351039:ios:4d9588282ce1da36fb568a',
    messagingSenderId: '557980351039',
    projectId: 'mopelis-ca195',
    storageBucket: 'mopelis-ca195.firebasestorage.app',
    iosBundleId: 'com.example.movil2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj4XyMCuZIPDJIU2lclg5k1yxseSKFQg4',
    appId: '1:557980351039:web:a3e34e21837a85fffb568a',
    messagingSenderId: '557980351039',
    projectId: 'mopelis-ca195',
    authDomain: 'mopelis-ca195.firebaseapp.com',
    storageBucket: 'mopelis-ca195.firebasestorage.app',
  );
}
